# Clave única de tu proyecto
sonar.projectKey=Java2303_AgroControl
sonar.organization=java2303

# Al estar parado dentro de desarrollo, la fuente es simplemente src
sonar.sources=src

# La ubicación de tus pruebas unitarias pasa a ser esta ruta limpia
sonar.tests=src/__test__

# Excluir el archivo de prueba del conteo de duplicados
sonar.test.inclusions=src/__test__/**/*.test.js

# Ubicación del reporte de cobertura
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Archivos excluidos del análisis
sonar.exclusions=**/node_modules/**,**/.next/**,**/coverage/**,package-lock.json