# Clave única de tu proyecto (la sacas de la URL de tu SonarCloud, en tu caso: Java2303_AgroControl)
sonar.projectKey=Java2303_AgroControl
sonar.organization=java2303

# Ubicación del código fuente y de las pruebas
sonar.sources=src
sonar.tests=tests

# Indicarle a Sonar dónde va a encontrar el reporte de cobertura de pruebas
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Archivos que no queremos que Sonar analice (librerías y archivos basura)
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,package-lock.json