sonar.projectKey=Java2303_AgroControl
sonar.organization=java2303

# Le indicamos la ruta completa ante el contenedor de GitHub
sonar.sources=desarrollo/src
sonar.tests=desarrollo/src/__test__

sonar.test.inclusions=desarrollo/src/__test__/**/*.test.js
sonar.javascript.lcov.reportPaths=desarrollo/coverage/lcov.info

sonar.exclusions=**/node_modules/**,**/.next/**,**/coverage/**,desarrollo/package-lock.json